### ISSUE TITLE
Week03Task07

### ISSUE THREAD

**Issue by KHajili98** [FikratMammadov/PragmatechCsharpProject#3]
task tam islenilmeyib... saitlerin sayini gosterilmir... 

- Clientdan bir soz daxil etmesini isteyin.Hemin sozun terkibinde sait seslerin ishlenib ishlenmediyini ve **_eger ishlenibse nece defe ishlendiyini tapib ekrana cixarin._**

**Comment by FikratMammadov** [comment]
bu task'da sehvlik yoxuydu mence. Zehmet olmasa yeniden baxarsiz.
