### ISSUE TITLE
Week03Task08

### ISSUE THREAD

**Issue by KHajili98** [FikratMammadov/PragmatechCsharpProject#4]
- 10 olculu int tipde array tanimlayin.0-dan 10-a qeder **_10 daxil olmamaqla_** random ededleri hemin arraye daxil edin. Note:bir ededi iki defe daxil etmek olmaz.Sonda yaranan array listi ve **_eyni ededden birden artiq yaranibsa onlarin sayini ekrana cixardin._**
- senin neticende hem 10 daxil edilib hem de eyni elave edilen elementlerin sayi bildirilmeyib. bir defe random eyni daxil edilen ededlerin sayi da gosterilmeli idi 

**_NETICEN:_**

Array elementleri:
8
6
5
1
3
4
9
2
7
10

**Comment by FikratMammadov** [comment]
task'da duzels etdim.
