### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by KHajili98** [FikratMammadov/PragmatechCsharpProject#5]
folderleri heftelere uygun bolusdursen ela olar... week01de butun tasklar ayri... week02 tasklari bir folder altinda, week03 ayri.. Novbeti heftede ona uygun sistemlesdir

**Comment by FikratMammadov** [comment]
folder structure-u duzeltdim

**Comment by KHajili98** [comment]
Aferin sonunda istediyim strukturu gordum..
